language: cpp
os:
- linux
install:
- echo "yes" | sudo add-apt-repository ppa:avsm/ocaml41+opam10
- travis_retry sudo apt-get update -qq; travis_retry sudo apt-get install ocaml -qq
script:
- sed -i "s|INSTALL_DIR=/usr|INSTALL_DIR=$PWD/dist/haxerb|" Makefile
- mkdir -p dist/haxerb/bin
- make
- make install
- cd dist; zip -q -r haxerb haxerb; cd ..
deploy:
  provider: releases
  api_key:
    secure: i109Iq34IA9QYF+Zf5WnieLzGdbbHlwl0QnHUXb4PKmB4vgTxwMRXSanPjM2I0/r5vuQiiuYuNTR6kfM6nbW6iyMjjoz/WB2W8/7LGCQCP8Fza46H18K2S3bEnvIPVQcfenjymPhoZ3JoTu9WubSj/LbDWZwPwqzP5Vb6HVwO9A=
  file: dist/haxerb.zip
  on:
    tags: true
    all_branches: true
